import counties from '../../data/counties.json';

const formData = {
  'Facility Details': [
    {
      name: 'facilityName',
      label: 'Name of Facility',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
    },
    {
      name: 'kmhflCode',
      label: 'KMHFL Code',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 6,
      },
    },
  ],
  'Client Details': [
    {
      name: 'ancCode',
      label: 'ANC Code',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'pncNumber',
      label: 'PNC No',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'clientName',
      label: 'Name of Client',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'dob',
      label: 'Date of Birth',
      type: 'date',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'phone',
      label: 'Phone Number',
      type: 'tel',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'educationLevel',
      label: 'Education Level',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: [
        'Primary School',
        'High School',
        'Undergraduate',
        'Postgraduate',
        'Tertiary',
        'None',
      ],
    },
    {
      name: 'maritalStatus',
      label: 'Marital Status',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: ['Married', 'Single', 'Divorced', 'Widowed'],
    },
  ],
  Residence: [
    {
      name: 'county',
      label: 'County',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: counties,
    },
    {
      name: 'subCounty',
      label: 'Sub-County',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: [],
    },
    {
      name: 'ward',
      label: 'Ward',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: [],
    },
    {
      name: 'estate',
      label: 'Estate',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: [],
    },
  ],
  'Next of Kin': [
    {
      name: 'nextOfKinName',
      label: 'Next of Kin Names',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'nextOfKinRelationship',
      label: 'Relationship',
      type: 'select',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
      options: ['Spouse', 'Parent', 'Sibling', 'Child', 'Other'],
    },
    {
      name: 'nextOfKinPhone',
      label: 'Phone Number',
      type: 'tel',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
  ],
  'Clinical Information': [
    {
      name: 'gravida',
      label: 'Gravida',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'parity',
      label: 'Parity',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'height',
      label: 'Height (cm)',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'weight',
      label: 'Weight (kg)',
      type: 'text',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
    {
      name: 'lmp',
      label: 'LMP',
      type: 'date',
      required: true,
      width: {
        xs: 12,
        sm: 12,
        md: 12,
        lg: 4,
      },
    },
  ],
};

export default formData;
